image: registry.gitlab.com/pages/hugo/hugo_extended

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  script:
  - hugo -b "https://jbjouvin.gitlab.io"
  artifacts:
    paths:
    - public
  only:
  - master

