baseurl = "https://jbjouvin.gitlab.io"
title = "jb"
languagecode = "en"
defaultcontentlanguage = "en"
paginate = 20
canonifyurls = true
pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
author = "JB"
info = "common guy"
description = "JB website"
keywords = "blog,developer,personal"
avatarurl = "images/jb.jpg"
footercontent = "Why do we fall ? So we can learn to pick ourselves up"
hidecredits = true
hidecopyright = true
rtl = false
math = true
colorscheme = "dark"
enableTwemoji = true

# Social links
[[params.social]]
name = "Github"
icon = "fab fa-github fa-2x"
weight = 1
url = "https://github.com/jbjouvin"

[[params.social]]
name = "Gitlab"
icon = "fab fa-gitlab fa-2x"
weight = 2
url = "https://gitlab.com/jbjouvin"

[[params.social]]
name = "Gitlab"
icon = "fab fa-linkedin fa-2x"
weight = 3
url = "https://fr.linkedin.com/in/jean-baptiste-jouvin-35773258"

[[params.social]]
name = "Resume"
icon = "far fa-file-alt fa-2x"
weight = 4
url = "http://jbjouvin.pro.s3-website-eu-west-1.amazonaws.com/"

# Menu links
[[menu.main]]
name = "blog"
weight = 1
url = "/posts/"

[[menu.main]]
name = "cheat-sheets"
weight = 2
url = "/cheat-sheets/"

[[menu.main]]
name = "Stracraft II"
weight = 3
url = "/sc2tips/"
